import axios from "axios";
import { toast } from "react-toastify";

// Centralized function for handling API errors.
// Instead of handling errors separately in every API call,
// we can call handleError(error).
export const handleError = (error: any) => {
  // Check whether the error was generated by Axios.
  if (axios.isAxiosError(error)) {
    // Get the response returned by the server.
    const err = error.response;

    // Handle errors returned as an array.
    if (Array.isArray(err?.data.errors)) {
      // Loop through every error returned by the API.
      for (let val of err?.data.errors) {
        // Display the error description to the user.
        toast.warning(val.description);
      }

      // Handle errors returned as an object.
    } else if (typeof err?.data.errors === "object") {
      // Loop through each property in the errors object.
      for (let e in err?.data.errors) {
        // Display the first validation error for that field.
        toast.warning(err.data.errors[e][0]);
      }

      // Handle a response that contains data directly.
    } else if (err?.data) {
      toast.warning(err.data);

      // Handle unauthorized requests.
    } else if (err?.status == 401) {
      // Tell the user that they need to log in.
      toast.warning("Please login");

      // Navigate the browser to the login page.
      window.history.pushState({}, "LoginPage", "/login");

      // Handle any other response from the server.
    } else if (err) {
      toast.warning(err?.data);
    }
  }
};
